# Generated by Django 3.2.3 on 2021-10-04 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('identificacion', models.BigIntegerField()),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('telefono', models.BigIntegerField()),
                ('fecha_inicial', models.DateField()),
                ('fecha_final', models.DateField()),
                ('valor', models.BigIntegerField()),
                ('comentario', models.TextField()),
                ('estado', models.BooleanField(default=True, verbose_name='estado')),
                ('ocultar', models.BooleanField(default=True, verbose_name='ocultar')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nombres'],
            },
        ),
    ]
